version: '3.4'

services:
  cs.dashboard:
    image: ${DOCKER_REGISTRY-}csdashboard
    container_name: dashboard
    build:
      context: .
      dockerfile: CS.DashBoard\Dockerfile
    environment:
     - CarSignalDb=Data Source=Data Source=185.161.208.160,33301;Initial Catalog=CarSignal;Integrated Security=False;User id=swed_q;Password=qwe159753@;MultipleActiveResultSets=True;
    networks:
      mynet:
        ipv4_address: 172.20.0.2

  signal.simulator:
    image: ${DOCKER_REGISTRY-}signalsimulator
    container_name: simulator
    build:
      context: .
      dockerfile: Signal.Simulator\Dockerfile
    environment:
     - CarSignalDb=Data Source=185.161.208.160,33301;Initial Catalog=CarSignal;Integrated Security=False;User id=swed_q;Password=qwe159753@;MultipleActiveResultSets=True;
    networks:
      mynet:
        ipv4_address: 172.20.0.3

networks:
  mynet:
    ipam:
      config:
        - subnet: 172.20.0.0/24  