version: '3.4'

services:
  #db:
  #  image: microsoft/mssql-server-windows-express
  #  container_name: database
  #  environment:
  #    sa_password: "Swedq159753"
  #    accept_eula: Y
  #    attach_dbs: '[{"dbName":"CarSignal","dbFiles":["c:\\sql\\CarSignal.mdf","c:\\sql\\CarSignal_log.ldf"]}]'
  #    command: powershell ./sql/InitBrocker.ps1
  #  volumes:
  #    - ./CS.InitSQL\:c:\sql\
  #  networks:
  #    frontend:
  #      ipv4_address: 172.20.0.5
  #  ports:
  #    - "1433:1433"

  cs.dashboard:
    image: ${DOCKER_REGISTRY-}csdashboard
    container_name: dashboard
    build:
      context: .
      dockerfile: CS.DashBoard\Dockerfile
    environment:
     - CarSignalDb=Data Source=185.161.208.161,33301;Initial Catalog=CarSignal;Integrated Security=False;User id=swed_q;Password=qwe159753@;
    networks:
      mynet:
        ipv4_address: 172.20.0.2

  signal.simulator:
    image: ${DOCKER_REGISTRY-}signalsimulator
    container_name: simulator
    build:
      context: .
      dockerfile: Signal.Simulator\Dockerfile
    environment:
     - CarSignalDb=Data Source=Data Source=185.161.208.161,33301;Initial Catalog=CarSignal;Integrated Security=False;User id=swed_q;Password=qwe159753@;
    networks:
      mynet:
        ipv4_address: 172.20.0.3

networks:
  mynet:
    ipam:
      config:
        - subnet: 172.20.0.0/24